### ISSUE TITLE
KeyError: 'country_code'

### ISSUE THREAD

**Issue by Rohan-Kar** [Lexxrt/FireFly#6]
`└──╼ $python3 FireFly.py +13213707446

  ______ _          ______ _       
 |  ____(_)        |  ____| |      
 | |__   _ _ __ ___| |__  | |_   _ 
 |  __| | | '__/ _ \  __| | | | | |
 | |    | | | |  __/ |    | | |_| |
 |_|    |_|_|  \___|_|    |_|\__, |
                              __/ |
                             |___/ 
        Author: Lexxrt
        Github: https://github.com/Lexxrt             

Traceback (most recent call last):
  File "FireFly.py", line 83, in <module>
    main()
  File "FireFly.py", line 27, in main
    country_code = obj['country_code']
KeyError: 'country_code'
`
I am getting this error please guide me on this .

**Comment by shri142** [comment]
same

**Comment by beni2a** [comment]
Hi, 
I have the same issue
tried to fix but unsuccess
Regards
